### ISSUE TITLE
[bug] sending a message to yourself yields a thread with last message having sender of null

### ISSUE THREAD

**Issue by kamikaz1k** [tarsil/django-messages-drf#5] opened 2021-01-11 20:52 UTC
When I send a message to myself, the `/inbox` response returns a thread with `last_message: null` and `sender: null`. 

Repro steps:
1. I am logged in as User<id=1>
2. I make a request to the send message endpoint
    `curl '/api/message/thread/1/send/'  '{"subject":"a thread subject","message":"this is a message!\n\nveronica@mars.com"}' ` 
3. Request is successful and returns the payload with the sender field correctly
    ```
    {
      "uuid": "aeb3e7c9-cacc-4182-95a1-00b17596e209",
      "sender": {
        "display_name": " ",
        "is_user": true
      },
      "sent_at": "2021-01-11T20:37:07.532471Z",
      "content": "this is a message!\n\nveronica@mars.com"
    }
    ```
4. But when you fetch `/inbox` it returns a thread with no sender:
    ```
    {
      ...
      "results": [
        {
          "uuid": "84ed87a9-7a75-43cc-93eb-265adfc03598",
          "subject": "a thread subject",
          "sender": null,
          "sent_at": "2021-01-11T20:37:07.532471Z",
          "total_unread": 1,
          "last_message": null
        },
        ...
      ]
    }
    ```
5. Fetching `/thread/84ed87a9-7a75-43cc-93eb-265adfc03598` directly yields the correct value for sender:
    ```
    {
      "subject": "a thread subject",
      "messages": [
        {
          "uuid": "aeb3e7c9-cacc-4182-95a1-00b17596e209",
          "sender": {
            "display_name": " ",
            "is_user": true
          },
          "sent_at": "2021-01-11T20:37:07.532471Z",
      "content": "this is a message!\n\nveronica@mars.com"
        }
      ]
    }
    ```

**Comment by tarsil** [comment] 2021-01-11 21:02
@kamikaz1k that is a good point and I think the behaviour is actually correct, my tests point that is the serializer the issue. 

I'm packing some changes and will be adding the serializer option from the settings and fix this as well. I just need t couple of days to run more tests.

Is this blocking you?

Again, thank you for your reports. This helps me a lot and I hope is still useful for you.

**Comment by kamikaz1k** [comment] 2021-01-12 03:04
It is not a blocker for now, since I sent the message to myself in error (😅 ). And if you are going to release a bug fix over the next week, that's fine by me. Thanks for all your hard work!

**Comment by tarsil** [comment] 2021-01-14 20:23
@kamikaz1k apologies for the delay but I was migrating the docs to something new and updating a few things by making ebeo more clear in the docs. I should release a new version soon as I'm running some more tests. I hope you didn't have any more problems but hopefully tomorrow a new version should be out.

**Comment by tarsil** [comment] 2021-01-15 16:15
@kamikaz1k I was able to add more unit tests, including the one you added here by replicating and I actually realized that is not a bug at all, actually is expected because you sent a message to yourself, and when we get the last message this piece of code runs

```python
def last_message(self, user_to_exclude=None):
        """
        Returns the latest message of the thread. Is the reverse of the `earliest_message`

        :param user_to_exclude: Returns a list of the messages excluding a given user. This is
        particulary useful for showing the latest message sent in a thread between two different
        users.
        """
        queryset = self.messages.all()
        try:
            if user_to_exclude:
                queryset = queryset.exclude(sender=user_to_exclude)
            return queryset.latest('sent_at')
        except Message.DoesNotExist:
            return
```

So basically you can't see the sender because I'm excluding it. I'm saying `Give me the latest message sent that wasn't from me`. This is particularly useful to see the latest message in a thread sent that is not from yourself but being honest I think it can be removed and allowed to see the latest sent message like a normal inbox because you were probably the last one sending it and expecting the reply.

So is not a "bug" but can be improved here. So I'm adding this functionality separately. This will be in docs already :)

**Comment by tarsil** [comment] 2021-01-15 17:03
@kamikaz1k I'm closing this issue as a new version of the lib which addresses some code cleaning and some issues you mentioned.
I also have in pipeline some possible new features but I need time as I also work fulltime. The issues are now fixed and the tests for your current case were added and passing.

https://tarsil.github.io/django-messages-drf/

**Closed as completed by tarsil** 2021-01-15 17:03 UTC
Labels: Going into the new release

**Comment by kamikaz1k** [comment] 2021-01-15 17:10
Docs look pretty! Thanks :)

**Comment by tarsil** [comment] 2021-01-15 17:11
Well, I love `mkdocs-material`. Not only it is a pleasure to write documentation but makes it look great. I also believe this is way more clear than the initial readme and can and will be improved maybe into new modules.
